version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:6.8.4
    container_name: elasticsearch
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - piggynet
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
  fluentd:
    image: registry.cn-hangzhou.aliyuncs.com/shenmiu/fluentd
    container_name: fluentd
    restart: always
    volumes:
      - ./fluentd/conf:/fluentd/etc
    networks:
      - piggynet
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch
    environment:
      - TZ=Asia/Shanghai
  kibana:
    image: kibana:6.8.4
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - TZ=Asia/Shanghai
      - discovery.type=single-node
    networks:
      - piggynet
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  oap:
    image: apache/skywalking-oap-server:6.5.0
    container_name: oap
    depends_on:
      - elasticsearch
    restart: always
    networks:
      - piggynet
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      - TZ=Asia/Shanghai
      - SW_STORAGE=elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200
  ui:
    image: registry.cn-hangzhou.aliyuncs.com/shenmiu/skywalking-rocketbot-ui
    container_name: ui
    restart: always
    networks:
      - piggynet
    ports:
      - 8080:80
    environment:
      - TZ=Asia/Shanghai
      - SKYWALKING_URL=oap:12800

  hello-world:
    image: registry.cn-hangzhou.aliyuncs.com/shenmiu/piggy-hello-world
    container_name: hello-world
    restart: always
    networks:
      - piggynet
    ports:
      - 8081:8081
    environment:
      - SW_SVC_NAME=hello-world
      - SW_URL=oap:11800
    # logging:
    #   driver: "fluentd"
    #   options:
    #     fluentd-address: localhost:24224
    #     fluentd-async-connect: "true"
    #     tag: hello-world

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - piggynet
    ports:
      - 9090:9090
    command: ["--config.file=/etc/prometheus/prometheus-static.yml"]
volumes:
  esdata:
    driver: local
networks:
  piggynet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.0.0/16